apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: production
data:
  PORT: "8000"
  NODE_ENV: "production"
  BASE_URL: "http://api.test.com"       
  FRONTEND_URL: "http://api.test.com"
     # update si tu a supprimer les ressourse groupes

