apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-storage-pvc
  namespace: production
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
